// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yskbbknfyjsgaitozwvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlza2Jia25meWpzZ2FpdG96d3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTU0NjYsImV4cCI6MjA2MTAzMTQ2Nn0.kQyzHzdpgoP7w4oFxDx5A9BcR_lD2qT63Cu8cyZk65E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);